//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int DealID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string RecipientNumber { get; set; }
        public string RecipientName { get; set; }
        public string Dimension { get; set; }
        public string Weight { get; set; }
        public string Contentt { get; set; }
        public Nullable<int> UserDealOfferIDMoasel { get; set; }
        public Nullable<int> DealOfferID { get; set; }
        public string FirstPassword { get; set; }
        public string SecoundPssword { get; set; }
        public Nullable<int> UserIDMorsel { get; set; }
        public string TypeOfDeal { get; set; }
    
        public virtual DealOffer DealOffer { get; set; }
        public virtual DealOffer DealOffer1 { get; set; }
        public virtual user user { get; set; }
    }
}
